# Generated by Django 5.1.2 on 2024-11-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_userproject_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userproject',
            table='UserProject',
        ),
    ]
